[package]
name = "taster"
version = "0.0.1"
authors = ["Malte Schwarzkopf <malte@csail.mit.edu>"]

[dependencies]
afterparty = { git = "https://github.com/ms705/afterparty.git" }
clap = "2.13"
env_logger = "0.3"
# openssl-sys version conflicts force us to use an old version of git2
git2 = "0.5.2"
hyper = "0.9"
lettre = "0.6.1"
log = "0.3"
regex = "0.1.80"
slack-hook = "0.2"
toml = "0.2.1"
