[package]
name = "taster"
version = "0.0.1"
authors = ["Malte Schwarzkopf <malte@csail.mit.edu>"]

[dependencies]
afterparty = { git = "https://github.com/ms705/afterparty.git" }
clap = "2.13"
env_logger = "0.3"
# afterparty doesn't work with hyper 0.9 until #14 is merged, so we use hyper v0.7
# hyper v0.7 is only compatible with git2 <v0.6
git2 = "0.5.2"
hyper = "0.7"
log = "0.3"
slack-hook = "0.2"
